_id: "387246620053340160"
model: gpt-3.5-turbo
createdAt: &a1 2023-12-05T14:19:48.915Z
updatedAt: *a1
createdBy: z1e32Au8HZgwiNMntL1vL9ZWfRNcRdUKZDD
updatedBy: z1e32Au8HZgwiNMntL1vL9ZWfRNcRdUKZDD
icon: http://dev.blocklet.mac.ipv6.yechao.xyz/image-bin/uploads/937950d97affe8e93df7523e1cc65929.png
gitType: default
temperature: 1
topP: 1
